name: Deploy InstantDomain

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Live Deployment
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
